FROM node:18-alpine

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install --production

# Copy backend source code
COPY api ./api
COPY common ./common

EXPOSE 5000

CMD ["npm", "run", "start:api"]
